spring:
  datasource:
    url: 'jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}'
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming: # for naming tables and colums exactly how are naming in existing DB
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hihernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    web:
      pageable:
        max-page-size: 2147483647
    
    
server:
  port: 8098
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: never
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
